---
- name: Make sure we have the postgresql apt repo installed
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main' state=present

- name: Install the postgresql apt repo key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

- name: Install postgresql
  apt: name={{ item }} state=present update_cache=yes
  with_items: postgresql_packages

- name: Copy configuration templates
  template: src=postgresql.conf.j2 dest=/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
  notify: reload postgres

- name: Copy pg_hba.conf 
  template: src=pg_hba.conf.j2 dest=/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
  notify: restart postgres
